@startuml
skinparam classAttributeIconSize 0

class file {
-createText
}

class program {
+text
getText
}

class words {
+text
+word
breaksTextIntoWords
}

class counter {
+adverb
+verb
+adjective
countNumberOfCertainPartOfSpeech
}

class noun {}
class adverb {}
class verb {}
class adjective {}
class preposition {}
class conjuction {}
class pronoun {}
class interjection {}
@enduml