@startuml
skinparam classAttributeIconSize 0

class file {
-createText
}

class program {
+text
}

class counter {
+adverb
+verb
+adjective
}

class noun {}
class adverb {}
class verb {}
class adjective {}
class preposition {}
class conjuction {}
class pronoun {}
class interjection {}
@enduml